# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Cisco-ObjectGroup
version:      0.04
version_from: lib/Net/Cisco/ObjectGroup.pm
installdirs:  site
requires:
    Class::Accessor:               0.25
    Class::Data::Inheritable:      0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
